### ISSUE TITLE
Criar tabela Points no banco de dados

### ISSUE THREAD

**Issue by victor-luiz** [sharkcodeEJ/sharkoleta#18]
Criar no banco de dados a tabela points, para persistências dos locais cadastrados, com os seguintes campos
 - id
 - name
 - email
 - whatsapp
 - latitude
 - longitude
 - number
 - city
 - uf 
 - image

**Comment by Gustavo-franca** [comment]
I believe that a better label for this issue would be task or config, as it does not add value to the user to the point of calling a feature
