### ISSUE TITLE
Configuração mobile RN com template Typescript

### ISSUE THREAD

**Issue by SousaFernando1** [sharkcodeEJ/sharkoleta#7]
- [x] Clonagem do repositório
- [x] Iniciar aplicativo (create-react-native-app)
- [x] Configuração Typescript
- [x] Configuração da máquina de testes (virtual ou físico)
- [x] Devolver alterações para o repositório remoto

**Comment by Gustavo-franca** [comment]
Caso não tiver mais requisitos , pode fechar a issue.

**Comment by SousaFernando1** [comment]
Pull request feito com sucesso.
